### ISSUE TITLE
Why are the implementation styles of forward and backward different?

### ISSUE THREAD

**Issue by qxzhou1010** [tlepoint/fhe.rs#189]
In `crates/fhe-math/src/zq/ntt.rs` , this file provides the implementation of `forward_vt` and `backward_vt`, where `forward_vt` calls `forward_lazy`, and then calls `reduce3`. However, in the implementation of `backward_vt`, the same pattern is not used. Why? 

Moreover, I read the codes of the `forward_vt` and `backward_vt` carefully and found that the two are not completely symmetrical, which has some deviations from my understanding of `NTT`. I always thought that **NTT forward and backward are completely symmetrical, the only difference is that the input is different.** Is there any more detailed material for the implementation here?

**Comment by Janmajayamall** [comment]
I believe with non-symmetry you are referring to multiplying inverse of `n` (size) [here](https://github.com/tlepoint/fhe.rs/blob/19ff18f8ab9ce291f830906aa931ce013c1ccfe0/crates/fhe-math/src/zq/ntt.rs#L170)? This is because inverse operation scales each element by `n`, so to counter the factor we multiply it by inverse of `n`.

**Comment by tlepoint** [comment]
Thanks for answering @Janmajayamall . You can find more information about the NTT and inverse NTT implementations at https://eprint.iacr.org/2018/039.pdf.
